name: Docker Image CI

on:
  push:
    branches:
    - main

jobs:

  docker:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag api:${{ github.sha }}
    - name: Deploy the docker image
      uses: elgohr/Publish-Docker-Github-Action@v4
      with:
        name: api:${{ github.sha }}
        username: ${{ secrets.DO_TOKEN }}
        password: ${{ secrets.DO_REGISTRY_PASSWORD }}
        registry: registry.digitalocean.com/safeops-challenge
